In [2]:
import pandas as pd

In [199]:
place = pd.read_csv('../ZZANG_PLACE.csv')

In [200]:
place.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16844 entries, 0 to 16843
Data columns (total 7 columns):
Unnamed: 0       16844 non-null int64
category         16844 non-null object
lat              16844 non-null float64
lon              16844 non-null float64
place_address    16523 non-null object
place_id         16844 non-null int64
place_name       16844 non-null object
dtypes: float64(2), int64(2), object(3)
memory usage: 921.2+ KB

In [201]:
facility = pd.read_csv('../ZZANG_FACILITY.csv')
facility.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112925 entries, 0 to 112924
Data columns (total 6 columns):
Unnamed: 0                 112925 non-null int64
facility_available_name    112925 non-null object
facility_is_available      108680 non-null object
place_name                 112925 non-null object
place_id                   112925 non-null int64
facility_id                112925 non-null int64
dtypes: int64(3), object(3)
memory usage: 5.2+ MB

In [202]:
facility.drop('Unnamed: 0', axis=1, inplace=True)

In [128]:
fac_per_placeid = facility.groupby('place_id', as_index=False).agg(lambda x : " ".join(x))

In [131]:
fac_per_placeid.drop('place_name',axis=1, inplace=True)

> 그룹바이로 값 묶어서 스트링을 입력값으로 넣을려고 했으나 해보니 안댐(KNN..).. 무조건 숫자값 들어가야 

# -----------------데이터 전처리!
> OneHotEncoder.. 쓸려고 했는데 어캐 쓰는지도 모르겠고 라벨링도 안되있어서
> 그냥 get_dummies인가? 쓰니까 뭔가 되서 그거 그룹바이해서 sum 하니깐 되서 걍 그렇게 함.

In [203]:
from sklearn.preprocessing import OneHotEncoder

In [204]:
facility.fillna('이용가능', inplace=True)

In [205]:
facility.isnull().sum()

facility_available_name    0
facility_is_available      0
place_name                 0
place_id                   0
facility_id                0
dtype: int64

In [206]:
facility.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112925 entries, 0 to 112924
Data columns (total 5 columns):
facility_available_name    112925 non-null object
facility_is_available      112925 non-null object
place_name                 112925 non-null object
place_id                   112925 non-null int64
facility_id                112925 non-null int64
dtypes: int64(2), object(3)
memory usage: 4.3+ MB

In [207]:
facility.sort_values('place_id')

,facility_available_name,facility_is_available,place_name,place_id,facility_id
112251,화장실,이용가능,가락시장,0,900000
112252,엘리베이터,이용가능,가락시장,0,900001
112253,휠체어리프트,이용가능,가락시장,0,900002
112255,화장실,이용가능,가산디지털단지,1,900004
112254,에스켈레이터,이용가능,가산디지털단지,1,900003
112257,휠체어리프트,이용가능,가산디지털단지,1,900006
112256,엘리베이터,이용가능,가산디지털단지,1,900005
112258,화장실,이용가능,강남,3,900007
112259,엘리베이터,이용가능,강남,3,900008
112260,에스켈레이터,이용가능,강남,3,900009
112264,휠체어리프트,이용가능,강남구청,4,900013
112261,에스켈레이터,이용가능,강남구청,4,900010
112263,엘리베이터,이용가능,강남구청,4,900012
112262,화장실,이용가능,강남구청,4,900011
112268,휠체어리프트,이용가능,강동,5,900017
112265,화장실,이용가능,강동,5,900014
112267,에스켈레이터,이용가능,강동,5,900016
112266,엘리베이터,이용가능,강동,5,900015
112269,화장실,이용가능,강동구청,6,900018
112270,엘리베이터,이용가능,강동구청,6,900019
112271,에스켈레이터,이용가능,강동구청,6,900020
112272,화장실,이용가능,강변,7,900021
112273,엘리베이터,이용가능,강변,7,900022
112274,휠체어리프트,이용가능,강변,7,900023
112275,화장실,이용가능,개농,8,900024
112276,엘리베이터,이용가능,개농,8,900025
112278,엘리베이터,이용가능,개화산,10,900027
112277,화장실,이용가능,개화산,10,900026
112279,화장실,이용가능,거여,11,900028
112280,에스켈레이터,이용가능,거여,11,900029
...,...,...,...,...,...
112220,남성용-대변기,이용가능,중랑물재생센터 화장실,31110,304214
112222,여성용-대변기,이용가능,중랑물재생센터 화장실,31110,304216
112224,남성용-소변기,이용가능,성수근린공원 화장실,31112,304218
112225,여성용-대변기,이용가능,성수근린공원 화장실,31112,304219
112223,남성용-대변기,이용가능,성수근린공원 화장실,31112,304217
112226,남성용-대변기,이용가능,독서당공원 화장실,31113,304220
112227,남성용-소변기,이용가능,독서당공원 화장실,31113,304221
112228,남성용-장애인용대변기,이용가능,독서당공원 화장실,31113,304222
112229,남성용-어린이용대변기,이용가능,독서당공원 화장실,31113,304223
112230,여성용-대변기,이용가능,독서당공원 화장실,31113,304224
112231,여성용-장애인용대변기,이용가능,독서당공원 화장실,31113,304225
112232,여성용-어린이용대변기,이용가능,독서당공원 화장실,31113,304226
112233,남성용-대변기,이용가능,왕십리문화공원 화장실,31114,304227
112235,남성용-장애인용대변기,이용가능,왕십리문화공원 화장실,31114,304229
112236,남성용-어린이용대변기,이용가능,왕십리문화공원 화장실,31114,304230
112237,여성용-대변기,이용가능,왕십리문화공원 화장실,31114,304231
112238,여성용-장애인용대변기,이용가능,왕십리문화공원 화장실,31114,304232
112239,여성용-어린이용대변기,이용가능,왕십리문화공원 화장실,31114,304233
112234,남성용-소변기,이용가능,왕십리문화공원 화장실,31114,304228
112242,남성용-장애인용대변기,이용가능,한양대 앞 화장실,31115,304236
112243,여성용-대변기,이용가능,한양대 앞 화장실,31115,304237
112240,남성용-대변기,이용가능,한양대 앞 화장실,31115,304234
112241,남성용-소변기,이용가능,한양대 앞 화장실,31115,304235
112244,남성용-대변기,이용가능,행당어린이공원 화장실,31116,304238
112245,남성용-소변기,이용가능,행당어린이공원 화장실,31116,304239
112246,남성용-장애인용대변기,이용가능,행당어린이공원 화장실,31116,304240
112247,남성용-어린이용대변기,이용가능,행당어린이공원 화장실,31116,304241
112248,여성용-대변기,이용가능,행당어린이공원 화장실,31116,304242
112249,여성용-장애인용대변기,이용가능,행당어린이공원 화장실,31116,304243
112250,여성용-어린이용대변기,이용가능,행당어린이공원 화장실,31116,304244

In [208]:
dummy = pd.get_dummies(facility, columns=['facility_available_name']).groupby(['place_id'], as_index=False).sum()

In [209]:
dummy = dummy.merge(place)

In [210]:
dummy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16202 entries, 0 to 16201
Data columns (total 51 columns):
place_id                                16202 non-null int64
facility_id                             16202 non-null int64
facility_available_name_ 음료대            16202 non-null uint8
facility_available_name_ 판매기            16202 non-null uint8
facility_available_name_객실 및 침실         16202 non-null uint8
facility_available_name_경보 및 피난설비       16202 non-null uint8
facility_available_name_계단 또는 승강설비      16202 non-null uint8
facility_available_name_계단핸드레일          16202 non-null uint8
facility_available_name_관람석 및 열람석       16202 non-null uint8
facility_available_name_남녀공용화장실         16202 non-null uint8
facility_available_name_남성용-대변기         16202 non-null uint8
facility_available_name_남성용-소변기         16202 non-null uint8
facility_available_name_남성용-어린이용대변기     16202 non-null uint8
facility_available_name_남성용-어린이용소변기     16202 non-null uint8
facility_available_name_남성용-장애인용대변기     16202 non-null uint8
facility_available_name_남성용-장애인용소변기     16202 non-null uint8
facility_available_name_대변기             16202 non-null uint8
facility_available_name_매표소             16202 non-null uint8
facility_available_name_복도              16202 non-null uint8
facility_available_name_비치용품            16202 non-null uint8
facility_available_name_샤워실 및 탈의실       16202 non-null uint8
facility_available_name_세면대             16202 non-null uint8
facility_available_name_소변기             16202 non-null uint8
facility_available_name_수평보행기           16202 non-null uint8
facility_available_name_에스켈레이터          16202 non-null uint8
facility_available_name_엘리베이터           16202 non-null uint8
facility_available_name_여성용-대변기         16202 non-null uint8
facility_available_name_여성용-어린이용대변기     16202 non-null uint8
facility_available_name_여성용-장애인용대변기     16202 non-null uint8
facility_available_name_욕실              16202 non-null uint8
facility_available_name_유도 및 안내 설비      16202 non-null uint8
facility_available_name_일반사항            16202 non-null uint8
facility_available_name_장애인 전용 주차구역     16202 non-null uint8
facility_available_name_장애인용 관람석        16202 non-null uint8
facility_available_name_장애인용 승강기        16202 non-null uint8
facility_available_name_장애인용 화장실        16202 non-null uint8
facility_available_name_장애인전용주차구역       16202 non-null uint8
facility_available_name_점자블록            16202 non-null uint8
facility_available_name_접수대 및 작업대       16202 non-null uint8
facility_available_name_주출입구 높이차이 제거    16202 non-null uint8
facility_available_name_주출입구 접근로        16202 non-null uint8
facility_available_name_출입구(문)          16202 non-null uint8
facility_available_name_해당시설 층수         16202 non-null uint8
facility_available_name_화장실             16202 non-null uint8
facility_available_name_휠체어리프트          16202 non-null uint8
Unnamed: 0                              16202 non-null int64
category                                16202 non-null object
lat                                     16202 non-null float64
lon                                     16202 non-null float64
place_address                           15978 non-null object
place_name                              16202 non-null object
dtypes: float64(2), int64(3), object(3), uint8(43)
memory usage: 1.8+ MB

In [211]:
dummy.drop(['Unnamed: 0', 'category', 'place_address'], inplace=True, axis=1)

In [212]:
dummy.columns

Index(['place_id', 'facility_id', 'facility_available_name_ 음료대',
       'facility_available_name_ 판매기', 'facility_available_name_객실 및 침실',
       'facility_available_name_경보 및 피난설비',
       'facility_available_name_계단 또는 승강설비', 'facility_available_name_계단핸드레일',
       'facility_available_name_관람석 및 열람석', 'facility_available_name_남녀공용화장실',
       'facility_available_name_남성용-대변기', 'facility_available_name_남성용-소변기',
       'facility_available_name_남성용-어린이용대변기',
       'facility_available_name_남성용-어린이용소변기',
       'facility_available_name_남성용-장애인용대변기',
       'facility_available_name_남성용-장애인용소변기', 'facility_available_name_대변기',
       'facility_available_name_매표소', 'facility_available_name_복도',
       'facility_available_name_비치용품', 'facility_available_name_샤워실 및 탈의실',
       'facility_available_name_세면대', 'facility_available_name_소변기',
       'facility_available_name_수평보행기', 'facility_available_name_에스켈레이터',
       'facility_available_name_엘리베이터', 'facility_available_name_여성용-대변기',
       'facility_available_name_여성용-어린이용대변기',
       'facility_available_name_여성용-장애인용대변기', 'facility_available_name_욕실',
       'facility_available_name_유도 및 안내 설비', 'facility_available_name_일반사항',
       'facility_available_name_장애인 전용 주차구역',
       'facility_available_name_장애인용 관람석', 'facility_available_name_장애인용 승강기',
       'facility_available_name_장애인용 화장실', 'facility_available_name_장애인전용주차구역',
       'facility_available_name_점자블록', 'facility_available_name_접수대 및 작업대',
       'facility_available_name_주출입구 높이차이 제거',
       'facility_available_name_주출입구 접근로', 'facility_available_name_출입구(문)',
       'facility_available_name_해당시설 층수', 'facility_available_name_화장실',
       'facility_available_name_휠체어리프트', 'lat', 'lon', 'place_name'],
      dtype='object')

In [213]:
dummy.columns = ['place_id', 'facility_id', '음료대',
       '판매기', '객실 및 침실',
       '경보 및 피난설비',
       '계단 또는 승강설비', '계단핸드레일',
       '관람석 및 열람석', '남녀공용화장실',
       '남성용-대변기', '남성용-소변기',
       '남성용-어린이용대변기',
       '남성용-어린이용소변기',
       '남성용-장애인용대변기',
       '남성용-장애인용소변기', '대변기',
       '매표소', '복도',
       '비치용품', '샤워실 및 탈의실',
       '세면대', '소변기',
       '수평보행기', '에스켈레이터',
       '엘리베이터', '여성용-대변기',
       '여성용-어린이용대변기',
       '여성용-장애인용대변기', '욕실',
       '유도 및 안내 설비', '일반사항',
       '장애인 전용 주차구역',
       '장애인용 관람석', '장애인용 승강기',
       '장애인용 화장실', '장애인전용주차구역',
       '점자블록', '접수대 및 작업대',
       '주출입구 높이차이 제거',
       '주출입구 접근로', '출입구(문)',
       '해당시설 층수', '화장실',
       '휠체어리프트', 'lat', 'lon', 'place_name']

In [214]:
dummy.drop('place_name', axis = 1, inplace=True)

In [229]:
dummy.drop('facility_id', axis = 1, inplace=True)

In [230]:
dummy.to_csv('dummy.csv')

In [217]:
#enc = OneHotEncoder()

In [218]:
#enc.fit(dummy)

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [222]:
#enc.feature_indices_

array([      0,   31117, 8186881, 8186883, 8186885, 8186887, 8186889,
       8186891, 8186893, 8186895, 8186897, 8186899, 8186901, 8186903,
       8186905, 8186907, 8186909, 8186911, 8186913, 8186915, 8186917,
       8186919, 8186921, 8186923, 8186925, 8186927, 8186929, 8186931,
       8186933, 8186935, 8186937, 8186939, 8186941, 8186947, 8186949,
       8186951, 8186953, 8186955, 8186957, 8186959, 8186965, 8186971,
       8186973, 8186975, 8186977, 8186979, 8187017, 8187145], dtype=int32)

In [231]:
dummy.describe()

,place_id,음료대,판매기,객실 및 침실,경보 및 피난설비,계단 또는 승강설비,계단핸드레일,관람석 및 열람석,남녀공용화장실,남성용-대변기,...,점자블록,접수대 및 작업대,주출입구 높이차이 제거,주출입구 접근로,출입구(문),해당시설 층수,화장실,휠체어리프트,lat,lon
count,16202.000000,16202.000000,16202.000000,16202.000000,16202.000000,16202.000000,16202.000000,16202.000000,16202.000000,16202.000000,...,16202.000000,16202.000000,16202.000000,16202.000000,16202.000000,16202.000000,16202.000000,16202.000000,16202.000000,16202.000000
mean,21308.680965,0.079805,0.079805,0.139859,0.189853,0.447290,0.000123,0.037897,0.006234,0.063511,...,0.121096,0.082150,0.888532,0.921738,0.625910,0.485743,0.013702,0.004999,37.547318,126.990740
std,7011.049124,0.270999,0.270999,0.346852,0.392197,0.497229,0.011110,0.190952,0.078710,0.243887,...,0.326249,0.274602,0.339442,0.327981,0.483902,0.499812,0.116254,0.070532,0.057011,0.088776
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,35.137559,126.495141
25%,14004.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,37.503258,126.918114
50%,23012.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,37.544168,127.007708
75%,27063.750000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,37.581079,127.056789
max,31116.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,5.000000,5.000000,1.000000,1.000000,1.000000,1.000000,37.699655,127.492149

In [232]:
dummy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16202 entries, 0 to 16201
Data columns (total 46 columns):
place_id        16202 non-null int64
음료대             16202 non-null uint8
판매기             16202 non-null uint8
객실 및 침실         16202 non-null uint8
경보 및 피난설비       16202 non-null uint8
계단 또는 승강설비      16202 non-null uint8
계단핸드레일          16202 non-null uint8
관람석 및 열람석       16202 non-null uint8
남녀공용화장실         16202 non-null uint8
남성용-대변기         16202 non-null uint8
남성용-소변기         16202 non-null uint8
남성용-어린이용대변기     16202 non-null uint8
남성용-어린이용소변기     16202 non-null uint8
남성용-장애인용대변기     16202 non-null uint8
남성용-장애인용소변기     16202 non-null uint8
대변기             16202 non-null uint8
매표소             16202 non-null uint8
복도              16202 non-null uint8
비치용품            16202 non-null uint8
샤워실 및 탈의실       16202 non-null uint8
세면대             16202 non-null uint8
소변기             16202 non-null uint8
수평보행기           16202 non-null uint8
에스켈레이터          16202 non-null uint8
엘리베이터           16202 non-null uint8
여성용-대변기         16202 non-null uint8
여성용-어린이용대변기     16202 non-null uint8
여성용-장애인용대변기     16202 non-null uint8
욕실              16202 non-null uint8
유도 및 안내 설비      16202 non-null uint8
일반사항            16202 non-null uint8
장애인 전용 주차구역     16202 non-null uint8
장애인용 관람석        16202 non-null uint8
장애인용 승강기        16202 non-null uint8
장애인용 화장실        16202 non-null uint8
장애인전용주차구역       16202 non-null uint8
점자블록            16202 non-null uint8
접수대 및 작업대       16202 non-null uint8
주출입구 높이차이 제거    16202 non-null uint8
주출입구 접근로        16202 non-null uint8
출입구(문)          16202 non-null uint8
해당시설 층수         16202 non-null uint8
화장실             16202 non-null uint8
휠체어리프트          16202 non-null uint8
lat             16202 non-null float64
lon             16202 non-null float64
dtypes: float64(2), int64(1), uint8(43)
memory usage: 1.2 MB

In [228]:
from sklearn.neighbors import NearestNeighbors

In [236]:
len(dummy.columns)

46

In [239]:
X = dummy.iloc[:, 1:]

In [241]:
nbrs = NearestNeighbors().fit(X)

In [277]:
t = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,37.48, 126.88]

In [278]:
print(nbrs.kneighbors([t]))

(array([[0.00272305, 0.02050345, 0.04185645, 0.04482714, 0.04758872]]), array([[  1,  48, 199, 165, 162]], dtype=int64))

In [280]:
dummy.iloc[48]

place_id         64.000000
음료대               0.000000
판매기               0.000000
객실 및 침실           0.000000
경보 및 피난설비         0.000000
계단 또는 승강설비        0.000000
계단핸드레일            0.000000
관람석 및 열람석         0.000000
남녀공용화장실           0.000000
남성용-대변기           0.000000
남성용-소변기           0.000000
남성용-어린이용대변기       0.000000
남성용-어린이용소변기       0.000000
남성용-장애인용대변기       0.000000
남성용-장애인용소변기       0.000000
대변기               0.000000
매표소               0.000000
복도                0.000000
비치용품              0.000000
샤워실 및 탈의실         0.000000
세면대               0.000000
소변기               0.000000
수평보행기             0.000000
에스켈레이터            1.000000
엘리베이터             1.000000
여성용-대변기           0.000000
여성용-어린이용대변기       0.000000
여성용-장애인용대변기       0.000000
욕실                0.000000
유도 및 안내 설비        0.000000
일반사항              0.000000
장애인 전용 주차구역       0.000000
장애인용 관람석          0.000000
장애인용 승강기          0.000000
장애인용 화장실          0.000000
장애인전용주차구역         0.000000
점자블록              0.000000
접수대 및 작업대         0.000000
주출입구 높이차이 제거      0.000000
주출입구 접근로          0.000000
출입구(문)            0.000000
해당시설 층수           0.000000
화장실               1.000000
휠체어리프트            1.000000
lat              37.493084
lon             126.895786
Name: 48, dtype: float64

In [284]:
place.iloc[48]

Unnamed: 0                       48
category          movie/concerthall
lat                         37.5833
lon                         127.005
place_address    서울특별시 종로구 동숭동 12-6
place_id                      10052
place_name                 대학로 단막극장
Name: 48, dtype: object